name: build snp-qemu
on:
  push:
    branches:
    - nested-snp-upm
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build-host-kernel:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: ccache
          uses: hendrikmuhs/ccache-action@v1.2
        - name: Build SNP qemu
          run: |
            ./run.sh
        - name: Archive artifacts
          uses: actions/upload-artifact@v2
          with:
            name: artifacts
            path: |
              snp-qemu*.*
              source-commit.*
